import { DataSchema } from "@/shared/types/query";

export const SCHEMAS: DataSchema[] = [
  {
    id: "users",
    name: "Users",
    fields: [
      { name: "id", label: "ID", type: "number" },
      { name: "name", label: "Name", type: "string" },
      { name: "email", label: "Email", type: "string" },
      { name: "age", label: "Age", type: "number" },
      { name: "country", label: "Country", type: "string" },
      {
        name: "status",
        label: "Status",
        type: "enum",
        enumValues: ["active", "inactive", "pending", "banned"],
      },
      { name: "purchases", label: "Purchases", type: "number" },
      { name: "createdAt", label: "Created At", type: "date" },
      { name: "isVerified", label: "Verified", type: "boolean" },
      {
        name: "plan",
        label: "Plan",
        type: "enum",
        enumValues: ["free", "pro", "enterprise"],
      },
    ],
  },
  {
    id: "products",
    name: "Products",
    fields: [
      { name: "id", label: "ID", type: "number" },
      { name: "name", label: "Name", type: "string" },
      { name: "price", label: "Price", type: "number" },
      { name: "stock", label: "Stock", type: "number" },
      { name: "sku", label: "SKU", type: "string" },
      {
        name: "category",
        label: "Category",
        type: "enum",
        enumValues: ["electronics", "clothing", "food", "books", "other"],
      },
      { name: "isActive", label: "Active", type: "boolean" },
      { name: "createdAt", label: "Created At", type: "date" },
    ],
  },
  {
    id: "orders",
    name: "Orders",
    fields: [
      { name: "id", label: "Order ID", type: "number" },
      { name: "userId", label: "User ID", type: "number" },
      { name: "total", label: "Total", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "enum",
        enumValues: [
          "pending",
          "processing",
          "shipped",
          "delivered",
          "cancelled",
        ],
      },
      { name: "itemCount", label: "Item Count", type: "number" },
      { name: "createdAt", label: "Created At", type: "date" },
      { name: "notes", label: "Notes", type: "string" },
    ],
  },
];

export const MOCK_DATA: Record<string, Record<string, unknown>[]> = {
  users: [
    {
      id: 1,
      name: "Amaka Obi",
      email: "amaka@example.com",
      age: 28,
      country: "Nigeria",
      status: "active",
      purchases: 15,
      createdAt: "2024-01-15",
      isVerified: true,
      plan: "pro",
    },
    {
      id: 2,
      name: "Chidi Nwosu",
      email: "chidi@example.com",
      age: 34,
      country: "Nigeria",
      status: "active",
      purchases: 42,
      createdAt: "2023-08-22",
      isVerified: true,
      plan: "enterprise",
    },
    {
      id: 3,
      name: "Fatima Al-Hassan",
      email: "fatima@example.com",
      age: 22,
      country: "Egypt",
      status: "pending",
      purchases: 3,
      createdAt: "2024-11-01",
      isVerified: false,
      plan: "free",
    },
    {
      id: 4,
      name: "Kofi Mensah",
      email: "kofi@example.com",
      age: 45,
      country: "Ghana",
      status: "inactive",
      purchases: 8,
      createdAt: "2022-05-10",
      isVerified: true,
      plan: "free",
    },
    {
      id: 5,
      name: "Ngozi Adeyemi",
      email: "ngozi@example.com",
      age: 31,
      country: "Nigeria",
      status: "active",
      purchases: 27,
      createdAt: "2023-12-03",
      isVerified: true,
      plan: "pro",
    },
    {
      id: 6,
      name: "Kwame Asante",
      email: "kwame@example.com",
      age: 19,
      country: "Ghana",
      status: "active",
      purchases: 1,
      createdAt: "2025-02-14",
      isVerified: false,
      plan: "free",
    },
    {
      id: 7,
      name: "Zara Musa",
      email: "zara@example.com",
      age: 52,
      country: "Kenya",
      status: "banned",
      purchases: 0,
      createdAt: "2021-07-30",
      isVerified: true,
      plan: "free",
    },
    {
      id: 8,
      name: "Emeka Eze",
      email: "emeka@example.com",
      age: 26,
      country: "Nigeria",
      status: "active",
      purchases: 56,
      createdAt: "2023-04-18",
      isVerified: true,
      plan: "enterprise",
    },
    {
      id: 9,
      name: "Aisha Diallo",
      email: "aisha@example.com",
      age: 38,
      country: "Senegal",
      status: "active",
      purchases: 12,
      createdAt: "2024-06-25",
      isVerified: true,
      plan: "pro",
    },
    {
      id: 10,
      name: "Tunde Bakare",
      email: "tunde@example.com",
      age: 17,
      country: "Nigeria",
      status: "pending",
      purchases: 0,
      createdAt: "2025-01-08",
      isVerified: false,
      plan: "free",
    },
    {
      id: 11,
      name: "Amara Sesay",
      email: "amara@example.com",
      age: 29,
      country: "Sierra Leone",
      status: "active",
      purchases: 9,
      createdAt: "2024-09-12",
      isVerified: true,
      plan: "pro",
    },
    {
      id: 12,
      name: "Bello Tanko",
      email: "bello@example.com",
      age: 41,
      country: "Nigeria",
      status: "inactive",
      purchases: 4,
      createdAt: "2022-11-28",
      isVerified: false,
      plan: "free",
    },
  ],
  products: [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 89.99,
      stock: 145,
      sku: "WH-001",
      category: "electronics",
      isActive: true,
      createdAt: "2024-01-10",
    },
    {
      id: 2,
      name: "Ankara Print Dress",
      price: 34.5,
      stock: 62,
      sku: "APD-002",
      category: "clothing",
      isActive: true,
      createdAt: "2024-03-22",
    },
    {
      id: 3,
      name: "JavaScript Deep Dive",
      price: 19.99,
      stock: 500,
      sku: "JDD-003",
      category: "books",
      isActive: true,
      createdAt: "2023-11-05",
    },
    {
      id: 4,
      name: "Organic Shea Butter",
      price: 12.0,
      stock: 0,
      sku: "OSB-004",
      category: "food",
      isActive: false,
      createdAt: "2023-06-18",
    },
    {
      id: 5,
      name: "Mechanical Keyboard",
      price: 149.0,
      stock: 38,
      sku: "MK-005",
      category: "electronics",
      isActive: true,
      createdAt: "2024-07-01",
    },
    {
      id: 6,
      name: "Linen Agbada Set",
      price: 67.0,
      stock: 25,
      sku: "LAS-006",
      category: "clothing",
      isActive: true,
      createdAt: "2024-05-15",
    },
    {
      id: 7,
      name: "Suya Spice Mix",
      price: 8.5,
      stock: 320,
      sku: "SSM-007",
      category: "food",
      isActive: true,
      createdAt: "2024-02-28",
    },
    {
      id: 8,
      name: "USB-C Hub",
      price: 39.99,
      stock: 90,
      sku: "UCH-008",
      category: "electronics",
      isActive: true,
      createdAt: "2024-08-14",
    },
  ],
  orders: [
    {
      id: 1001,
      userId: 1,
      total: 89.99,
      status: "delivered",
      itemCount: 1,
      createdAt: "2025-01-05",
      notes: "",
    },
    {
      id: 1002,
      userId: 2,
      total: 289.48,
      status: "shipped",
      itemCount: 4,
      createdAt: "2025-04-12",
      notes: "Priority shipping",
    },
    {
      id: 1003,
      userId: 5,
      total: 54.49,
      status: "processing",
      itemCount: 2,
      createdAt: "2025-05-28",
      notes: "",
    },
    {
      id: 1004,
      userId: 8,
      total: 427.94,
      status: "delivered",
      itemCount: 6,
      createdAt: "2025-03-20",
      notes: "",
    },
    {
      id: 1005,
      userId: 3,
      total: 19.99,
      status: "pending",
      itemCount: 1,
      createdAt: "2025-05-30",
      notes: "",
    },
    {
      id: 1006,
      userId: 4,
      total: 0,
      status: "cancelled",
      itemCount: 3,
      createdAt: "2025-02-14",
      notes: "Customer cancelled",
    },
    {
      id: 1007,
      userId: 9,
      total: 149.0,
      status: "delivered",
      itemCount: 1,
      createdAt: "2025-01-22",
      notes: "",
    },
    {
      id: 1008,
      userId: 11,
      total: 78.49,
      status: "shipped",
      itemCount: 3,
      createdAt: "2025-05-25",
      notes: "",
    },
  ],
};
